<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-R9PDO4C" ignored="3" name="firefox" tests="1" failures="1" timestamp="17 Nov 2017 06:43:42 GMT" time="28.035" errors="0">
  <testcase name="deleteDictionary" time="5.955" classname="com.selenium.unittest.max.Dictionary">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.selenium.unittest.max.Dictionary.deleteDictionary(Dictionary.java:221)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- deleteDictionary -->
  <testcase name="nameDictionaryMoreThan255" time="0.0" classname="com.selenium.unittest.max.Dictionary">
    <ignored/>
  </testcase> <!-- nameDictionaryMoreThan255 -->
  <testcase name="createDictionary" time="0.0" classname="com.selenium.unittest.max.Dictionary">
    <ignored/>
  </testcase> <!-- createDictionary -->
  <testcase name="nameDictionary" time="0.0" classname="com.selenium.unittest.max.Dictionary">
    <ignored/>
  </testcase> <!-- nameDictionary -->
</testsuite> <!-- firefox -->
